const {test}=require('node:test');const assert=require('node:assert/strict');
const {createRecoveryService,resetSchema}=require('../src/services/password-recovery.service');
const {registerSchema}=require('../src/schemas/auth.schema');
const crypto=require('node:crypto');
function setup(overrides={}){const sent=[];const tokens=new Map();const repo={throttle:async()=>true,issue:async(email,hash)=>{if(email!=='known@example.test')return false;tokens.set(hash,true);return true;},revoke:async hash=>tokens.delete(hash),consume:async hash=>tokens.delete(hash)};const mail={enabled:true,sendPasswordReset:async message=>sent.push(message)};return {sent,tokens,repo,mail,service:createRecoveryService({repo,mail,origin:()=> 'https://observatorio.example.test',wait:async()=>{},...overrides})};}
test('correo no configurado devuelve 503 sin consultar ni emitir enlaces',async()=>{const {service,tokens}=setup({mail:{enabled:false}});assert.equal(service.available(),false);await assert.rejects(service.request({email:'known@example.test'},'ip'),e=>e.statusCode===503);assert.equal(tokens.size,0);});
test('origen de correo requiere dominio fijo seguro y no acepta redirecciones',()=>{for(const value of ['http://unsafe.example','https://u:p@example.test','https://example.test/?next=x','garbage'])assert.equal(setup({origin:()=>value}).service.available(),false);});
test('solicitud no expone cuenta ni token y almacena sólo su hash',async()=>{const {service,sent,tokens}=setup();assert.equal(await service.request({email:'known@example.test'},'ip'),undefined);assert.equal(await service.request({email:'missing@example.test'},'ip'),undefined);assert.equal(sent.length,1);const url=new URL(sent[0].url);assert.equal(url.search,'');const token=new URLSearchParams(url.hash.slice(1)).get('token');assert.match(token,/^[a-f0-9]{64}$/);assert.equal(tokens.has(token),false);assert.equal(tokens.has(crypto.createHash('sha256').update(token).digest('hex')),true);});
test('fallo de correo invalida el enlace sin divulgar la cuenta',async()=>{const {service,mail,tokens}=setup();mail.sendPasswordReset=async()=>{throw Error('provider secret');};await service.request({email:'known@example.test'},'ip');assert.equal(tokens.size,0);});
test('enlace no puede reutilizarse y se validan contraseña y campos',async()=>{const {service,sent}=setup();await service.request({email:'known@example.test'},'ip');const token=new URLSearchParams(new URL(sent[0].url).hash.slice(1)).get('token');await service.reset({token,password:'NewPassword123!'},'ip');await assert.rejects(service.reset({token,password:'NewPassword123!'},'ip'),e=>e.errorCode==='RESET_LINK_INVALID');assert.equal(resetSchema.safeParse({token,password:'weak'}).success,false);assert.equal(resetSchema.safeParse({token,password:'NewPassword123!',email:'extra'}).success,false);});
test('límite de intentos devuelve 429 y no manda correo',async()=>{const {service,repo,sent}=setup();repo.throttle=async()=>false;await assert.rejects(service.request({email:'known@example.test'},'ip'),e=>e.statusCode===429);assert.equal(sent.length,0);});
test('registro requiere aceptar la versión vigente sin asignarla a cuentas previas',()=>{const input={firstName:'Ana',lastName:'Prueba',email:'ana@example.test',password:'Password123!'};assert.equal(registerSchema.safeParse(input).success,false);assert.equal(registerSchema.safeParse({...input,termsVersion:'old'}).success,false);assert.equal(registerSchema.safeParse({...input,termsVersion:'2026-09-11'}).success,true);});
