import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useForm } from "react-hook-form";
import { Link, useNavigate, useParams } from "react-router-dom";
import { isApiError } from "@/api";
import { Button } from "@/components/ui/Button";
import { PageFeedback } from "@/components/feedback/PageFeedback";
import { FieldHelp, FieldLabel } from "@/components/forms/FieldHelp";
import { useAuth } from "@/features/auth/AuthContext";
import { getAdminEntity } from "../admin.service";
import { createTrend, getTrendFormOptions, linkTrendRelations, unlinkTrendRelation, updateTrend } from "./trend-form.service";
import type { Option, Trend, TrendFormOptions } from "./trend-form.types";
import {TrendAssessmentField} from "@/features/assessment/TrendAssessmentField";
import type {TrendAssessment,TrendEvidence} from "@/features/assessment/trend-assessment";
import styles from "../signals/SignalForm.module.css";

type Values = { title:string; narrative:string; implications:string; assessment:TrendAssessment|null; methodologyNotes:string; signalIds:string[]; actorIds:string[] };
const EMPTY: Values = { title:"", narrative:"", implications:"", assessment:null, methodologyNotes:"", signalIds:[], actorIds:[] };
const valuesFrom = (trend: Trend): Values => ({ title:trend.title, narrative:trend.narrative, implications:trend.implications ?? "", assessment:trend.assessment??null, methodologyNotes:trend.methodologyNotes ?? "", signalIds:trend.signals.map((v)=>String(v.id)), actorIds:trend.actors.map((v)=>String(v.id)) });
const nullable = (value:string) => value.trim() || null;

function Checks({ label, name, options, register, disabled }: { label:string; name:"signalIds"|"actorIds"; options:Option[]; register:ReturnType<typeof useForm<Values>>["register"]; disabled?:boolean }) {
  return <fieldset className={`${styles.field} ${styles.wide}`} disabled={disabled}><legend>{label} <FieldHelp>{name === "signalIds" ? "Vincula sólo señales validadas del mismo FCV o categorías relacionadas, con coherencia temporal y de dirección." : "Selecciona actores directamente relacionados con el patrón."}</FieldHelp></legend>{options.length === 0 ? <p>No hay opciones disponibles.</p> : options.map((option)=><label key={option.value}><input type="checkbox" value={option.value} {...register(name)} /> {option.label}</label>)}</fieldset>;
}

function TrendForm({ initial, mode, options, trend }: { initial:Values; mode:"create"|"edit"; options:TrendFormOptions; trend?:Trend }) {
  const auth=useAuth(); const navigate=useNavigate(); const queryClient=useQueryClient(); const {register,handleSubmit,setError,setValue,watch,clearErrors,formState:{errors}}=useForm<Values>({defaultValues:initial});
  const mutation=useMutation({mutationFn:async(values:Values)=>{
    const scalar={title:values.title.trim(),narrative:values.narrative.trim(),implications:nullable(values.implications),assessment:values.assessment!,methodologyNotes:nullable(values.methodologyNotes)};
    if(mode==="create") return createTrend({...scalar,signalIds:values.signalIds.map(Number),actorIds:values.actorIds.map(Number)},auth.token!);
    const response=await updateTrend(trend!.id,{...scalar,updatedAt:trend!.updatedAt},auth.token!);
    const sync=async(relation:"signals"|"actors",current:number[],next:number[])=>{const added=next.filter((id)=>!current.includes(id));const removed=current.filter((id)=>!next.includes(id));await linkTrendRelations(trend!.id,relation,added,auth.token!);for(const id of removed)await unlinkTrendRelation(trend!.id,relation,id,auth.token!);};
    if(auth.hasPermission("trends:link-signals")) await sync("signals",trend!.signals.map((v)=>Number(v.id)),values.signalIds.map(Number));
    await sync("actors",trend!.actors.map((v)=>Number(v.id)),values.actorIds.map(Number)); return response;
  }});
  const submit=handleSubmit(async(values)=>{if(!values.title.trim())setError("title",{message:"Escribe el título."});else if(!values.narrative.trim())setError("narrative",{message:"Escribe la narrativa."});else if(!values.assessment)setError("assessment",{message:"Completa la valoración de la tendencia."});else try{const response=await mutation.mutateAsync(values);await Promise.all([queryClient.invalidateQueries({queryKey:["admin-entities","trends"]}),queryClient.invalidateQueries({queryKey:["admin-entity","trends",response.data.id]})]);navigate(`/admin/tendencias/${response.data.id}`);}catch{/* rendered */}});
  const apiError=mutation.error&&isApiError(mutation.error)?mutation.error:null;
  return <form className={styles.form} noValidate onSubmit={submit}>{mutation.isError&&<div className={styles.summary} role="alert">{apiError?.status===409?"La tendencia cambió en otra sesión. Recarga la versión actual antes de guardar.":apiError?.message??"No fue posible guardar la tendencia."}</div>}
    <section className={styles.section}><h2>Análisis</h2><div className={styles.grid}><div className={`${styles.field} ${styles.wide}`}><FieldLabel help="Nombra el patrón observado, no una señal individual ni una predicción definitiva." htmlFor="trend-title">Título</FieldLabel><input id="trend-title" maxLength={200} {...register("title")}/>{errors.title&&<small className={styles.error}>{errors.title.message}</small>}</div><div className={`${styles.field} ${styles.wide}`}><FieldLabel help="Explica qué está cambiando, qué señales convergen y por qué forman un patrón coherente." htmlFor="trend-narrative">Narrativa</FieldLabel><textarea id="trend-narrative" maxLength={10000} rows={8} {...register("narrative")}/>{errors.narrative&&<small className={styles.error}>{errors.narrative.message}</small>}</div><div className={`${styles.field} ${styles.wide}`}><FieldLabel help="Describe consecuencias probables para Querétaro y México, actores y decisiones afectadas." htmlFor="trend-implications">Implicaciones</FieldLabel><textarea id="trend-implications" maxLength={10000} rows={5} {...register("implications")}/></div></div></section>
    <section className={styles.section}><h2>Clasificación metodológica</h2><div className={styles.grid}><div className={`${styles.field} ${styles.wide}`}><FieldLabel help="Documenta exclusiones, contradicciones y justificación. No se publica." htmlFor="trend-notes">Notas metodológicas</FieldLabel><textarea id="trend-notes" maxLength={5000} rows={4} {...register("methodologyNotes")}/></div></div></section>
    <TrendAssessmentField value={watch("assessment")} signals={options.signals.filter(v=>watch("signalIds").includes(v.value)).flatMap<TrendEvidence>(v=>v.evidence?[v.evidence]:[])} error={errors.assessment?.message} onChange={v=>{setValue("assessment",v,{shouldDirty:true});clearErrors("assessment");}} /><section className={styles.section}><h2>Evidencia y actores</h2><div className={styles.grid}><Checks disabled={mode==="edit"&&!auth.hasPermission("trends:link-signals")} label="Señales validadas" name="signalIds" options={options.signals} register={register}/><Checks label="Actores relacionados" name="actorIds" options={options.actors} register={register}/></div></section>
    <div className={styles.actions}><Link to={trend?`/admin/tendencias/${trend.id}`:"/admin/tendencias"}>Cancelar</Link><Button disabled={mutation.isPending} type="submit" variant="primary">{mutation.isPending?"Guardando…":mode==="create"?"Crear tendencia":"Guardar cambios"}</Button></div></form>;
}

export function TrendFormPage({mode}:{mode:"create"|"edit"}){const auth=useAuth();const navigate=useNavigate();const raw=useParams().id;const id=raw&&/^\d+$/.test(raw)?Number(raw):null;const options=useQuery({queryKey:["trend-form-options"],queryFn:({signal})=>getTrendFormOptions(auth.token!,signal)});const detail=useQuery({queryKey:["admin-entity","trends",id],queryFn:({signal})=>getAdminEntity("trends",id!,auth.token!,signal),enabled:mode==="edit"&&Boolean(id)});const trend=detail.data?.data as Trend|undefined;const owner=trend?.analyst?.id===auth.user?.id;const editable=trend?.status.code==="NEW"&&(owner||auth.hasPermission("trends:validate"));if(mode==="edit"&&!id)return <PageFeedback title="Tendencia no disponible" message="El identificador no es válido."/>;if(options.isPending||(mode==="edit"&&detail.isPending))return <PageFeedback title="Preparando formulario" message="Consultando catálogos, señales, actores y versión actual."/>;if(options.isError||(mode==="edit"&&detail.isError))return <PageFeedback title="Formulario no disponible" message="No fue posible consultar los datos necesarios."/>;if(mode==="edit"&&(!trend||!editable))return <PageFeedback title="Edición no permitida" message="Sólo el analista responsable o un validador pueden editar tendencias nuevas." actionLabel="Volver" onAction={()=>navigate("/admin/tendencias")}/>;return <section className={styles.page}><header className={styles.header}><div><h1>{mode==="create"?"Nueva tendencia":`Editar ${trend!.businessCode}`}</h1><p>Integra narrativa, clasificación y evidencia validada.</p></div>{trend&&<div className={styles.ips}><span>Madurez sugerida</span><strong>{trend.suggestedMaturity.code??"Sin evidencia suficiente"}</strong></div>}</header><TrendForm initial={trend?valuesFrom(trend):EMPTY} key={trend?.updatedAt??"new"} mode={mode} options={options.data!} trend={trend}/></section>}
export const CreateTrendFormPage=()=> <TrendFormPage mode="create"/>;
export const EditTrendFormPage=()=> <TrendFormPage mode="edit"/>;
