import {useEffect,useState,type FormEvent} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Link,useLocation} from 'react-router-dom';
import {apiRequest,isApiError} from '@/api';
import {Button} from '@/components/ui/Button';
import {TextField} from '@/components/forms/TextField';
import {useAuth} from './AuthContext';
import {resetPasswordFormSchema} from './auth.schemas';
import styles from './AuthForm.module.css';
interface Response {message:string;data:{available:boolean}}
export function ForgotPasswordPage(){
 const [email,setEmail]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');
 const status=useQuery({queryKey:['password-recovery-status'],queryFn:({signal})=>apiRequest<Response>('/auth/password/status',{signal}),staleTime:0,retry:false});
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const result=await apiRequest<Response>('/auth/password/forgot',{method:'POST',body:{email:email.trim()}});setMessage(result.message);}catch(e){setError(isApiError(e)?e.message:'No fue posible enviar la solicitud. Inténtalo de nuevo.');}finally{setBusy(false);}}
 return <section className={styles.page}><header className={styles.header}><h1>Recuperar contraseña</h1><p>Escribe el correo de tu cuenta para solicitar un enlace de un solo uso. El enlace tendrá una vigencia de 30 minutos.</p></header>{status.isPending?<p role="status">Comprobando disponibilidad…</p>:status.isError?<div className={styles.errorSummary} role="alert">No pudimos comprobar la disponibilidad. <button onClick={()=>void status.refetch()}>Reintentar</button></div>:!status.data.data.available?<div className={styles.sessionNotice} role="status"><strong>Recuperación por correo aún no disponible</strong><span>El envío de correo todavía no está habilitado. Inténtalo más adelante. No se ha enviado ningún mensaje.</span></div>:message?<div className={styles.sessionNotice} role="status"><strong>Solicitud recibida</strong><span>{message}</span><button onClick={()=>{setMessage('');setEmail('');}}>Usar otro correo</button></div>:null}
 {!message&&<form className={styles.form} onSubmit={submit}>{error&&<p className={styles.errorSummary} role="alert">{error}</p>}<TextField label="Correo electrónico" autoComplete="email" type="email" required maxLength={150} value={email} onChange={e=>setEmail(e.target.value)} disabled={status.data?.data.available!==true||busy}/><Button type="submit" variant="primary" disabled={status.data?.data.available!==true||busy}>{busy?'Solicitando enlace…':'Enviar enlace de recuperación'}</Button></form>}<p className={styles.alternative}><Link to="/iniciar-sesion">Volver a iniciar sesión</Link></p></section>;
}
export function ResetPasswordPage(){const location=useLocation();return <ResetPasswordForm key={location.hash} initialHash={location.hash}/>;}
function ResetPasswordForm({initialHash}:{initialHash:string}){
 const auth=useAuth();
 const [token]=useState(()=>new URLSearchParams(initialHash.slice(1)).get('token')??'');
 const [password,setPassword]=useState('');const [confirmPassword,setConfirmPassword]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [done,setDone]=useState(false);const [invalid,setInvalid]=useState(!/^[a-f0-9]{64}$/.test(token));
 useEffect(()=>{window.history.replaceState(window.history.state,'',window.location.pathname);const meta=document.createElement('meta');meta.name='referrer';meta.content='no-referrer';document.head.appendChild(meta);return()=>meta.remove();},[]);
 async function submit(e:FormEvent){e.preventDefault();setError('');const parsed=resetPasswordFormSchema.safeParse({password,confirmPassword});if(!parsed.success){setError(parsed.error.issues[0].message);return;}setBusy(true);try{await apiRequest('/auth/password/reset',{method:'POST',body:{token,password}});auth.logout();setPassword('');setConfirmPassword('');setDone(true);}catch(e){if(isApiError(e)&&e.code==='RESET_LINK_INVALID')setInvalid(true);setError(isApiError(e)?e.message:'No fue posible cambiar la contraseña. Inténtalo de nuevo.');}finally{setBusy(false);}}
 return <section className={styles.page}><header className={styles.header}><h1>Restablecer contraseña</h1><p>Elige una contraseña nueva para tu cuenta.</p></header>{done?<div className={styles.sessionNotice} role="status"><strong>Contraseña actualizada</strong><span>Las sesiones anteriores se cerraron. Inicia sesión con tu nueva contraseña.</span></div>:invalid?<div className={styles.errorSummary} role="alert">El enlace no es válido, ha caducado o ya fue utilizado. <Link to="/recuperar-contrasena">Solicitar otro enlace</Link></div>:<form className={styles.form} onSubmit={submit}>{error&&<p role="alert" className={styles.errorSummary}>{error}</p>}<TextField label="Nueva contraseña" hint="Mínimo 8 caracteres, con mayúscula, minúscula y número." type="password" autoComplete="new-password" required maxLength={100} value={password} onChange={e=>setPassword(e.target.value)}/><TextField label="Confirmar nueva contraseña" type="password" autoComplete="new-password" required maxLength={100} value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)}/><Button type="submit" variant="primary" disabled={busy}>{busy?'Guardando…':'Guardar nueva contraseña'}</Button></form>}<p className={styles.alternative}><Link to="/iniciar-sesion">Volver a iniciar sesión</Link></p></section>;
}
