version: "3.9"

services:

  postgres:
    image: postgres:17
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d
      - ./database:/scripts

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - observatorio

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile

    env_file:
      - .env

    environment:
      MEDIA_ROOT: /app/storage/media

    volumes:
      - media_data:/app/storage/media

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - observatorio

  frontend:
    build:
      context: ./client
      dockerfile: ../docker/frontend/Dockerfile

    env_file:
      - .env

    networks:
      - observatorio

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile

    depends_on:
      - frontend
      - backend

    networks:
      - observatorio

volumes:
  postgres_data:
  media_data:

networks:
  observatorio:
