import {cleanup,fireEvent,render,screen} from '@testing-library/react';
import {afterEach,expect,it,vi} from 'vitest';
import {SignalFilters} from './SignalFilters';
import {parseSignalFilters} from './signal-filters';
import {ContentFilters} from '../content/ContentFilters';
import {parseContentFilters} from '../content/content-filters';
afterEach(cleanup);
for (const kind of ['signals','content']) it(`${kind}: overlays relacionados conservan selecciones`,()=>{
 const apply=vi.fn();
 const catalogs={types:[],fcv:[{code:'TEC',name:'Tecnología'},{code:'MER',name:'Mercado'}],categories:[{id:1,name:'Nodos',fcvCode:'TEC'},{id:2,name:'Ciclos',fcvCode:'MER'}]};
 const params=new URLSearchParams('fcv=TEC&categoryId=1');
 render(kind==='signals'?<SignalFilters filters={parseSignalFilters(params)} catalogs={catalogs} onApply={apply} onClear={()=>{}}/>:<ContentFilters filters={parseContentFilters(params)} catalogs={catalogs} onApply={apply} onClear={()=>{}}/>);
 expect(screen.queryByRole('checkbox')).toBeNull();
 const factors=screen.getByRole('button',{name:/Seleccionar factores/});
 expect(factors.closest('details')).toBeNull();
 fireEvent.click(factors);
 fireEvent.click(screen.getByLabelText('Mercado'));
 fireEvent.click(screen.getByText('Listo'));
 expect(screen.queryByRole('dialog')).toBeNull();
 expect(factors).toHaveFocus();
 const categories=screen.getByRole('button',{name:/Seleccionar categorías/});
 expect(categories.closest('details')).not.toBeNull();
 fireEvent.click(categories);
 expect(screen.getByLabelText('Nodos')).toBeChecked();
 fireEvent.click(screen.getByLabelText('Ciclos'));
 fireEvent.click(screen.getByText('Listo'));
 fireEvent.click(screen.getByText('Aplicar filtros'));
 expect(apply.mock.calls[0][0].get('fcvCodes')).toBe('TEC,MER');
 expect(apply.mock.calls[0][0].get('categoryIds')).toBe('1,2');
 fireEvent.click(factors);
 fireEvent.click(screen.getByLabelText('Tecnología'));
 fireEvent.click(screen.getByText('Listo'));
 fireEvent.click(categories);
 expect(screen.queryByLabelText('Nodos')).toBeNull();
 expect(screen.getByLabelText('Ciclos')).toBeChecked();
 fireEvent.click(screen.getByText('Listo'));
 fireEvent.click(screen.getByText('Aplicar filtros'));
 expect(apply.mock.calls[1][0].get('categoryIds')).toBe('2');
});
