import {useState,type FormEvent} from 'react';
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query';
import {Link,useNavigate,useParams,useSearchParams} from 'react-router-dom';
import {useAuth} from '@/features/auth/AuthContext';
import {PageFeedback} from '@/components/feedback/PageFeedback';
import {isApiError} from '@/api';
import {MediaLibrary} from '@/features/admin/media/MediaLibrary';
import {DOMAINS,STATUS,isDomain,type Domain} from './config';
import {listRecords,getRecord,request,type DataRecord,type RecordInput,type HistoryItem,type Page} from './service';
import {RecordDetails,RecordMetadata,EventPhoto} from './PublicDataPage';
import styles from './Observatory.module.css';

const actions=[['SUBMIT','Enviar a revisión','DRAFT','data:submit'],['APPROVE','Aprobar','IN_REVIEW','data:approve'],['REJECT','Devolver a borrador','IN_REVIEW','data:approve'],['PUBLISH','Publicar','APPROVED','data:publish'],['ARCHIVE','Archivar','PUBLISHED','data:publish'],['REOPEN','Reabrir como borrador','ARCHIVED','data:update']] as const;
function ErrorNotice({error}:{error:unknown}){return error?<div role="alert" className={styles.error}>{isApiError(error)?<>{error.status===409?'El registro cambió. Recarga antes de continuar.':error.message}<ul>{error.details.map((e,i)=><li key={i}>{e.message}</li>)}</ul></>:error instanceof Error?error.message:'No fue posible completar la operación.'}</div>:null;}
export function AdminDataPage(){const {kind,id}=useParams();return isDomain(kind)?<AdminDomain key={`${kind}-${id??'list'}`} kind={kind} id={id}/>:<PageFeedback title="Dominio no disponible" message="Selecciona un módulo de datos."/>;}
function AdminDomain({kind,id}:{kind:Domain;id?:string}){
  const auth=useAuth();const navigate=useNavigate();const qc=useQueryClient();const [params,setParams]=useSearchParams();const [search,setSearch]=useState(params.get('search')??'');
  const filters=new URLSearchParams();for(const key of ['search','status','page'])if(params.get(key))filters.set(key,params.get(key)!);
  const listing=useQuery({queryKey:['admin-data',kind,filters.toString(),auth.user?.id],queryFn:({signal})=>listRecords(kind,filters,auth.token,signal),enabled:!id});
  const detail=useQuery({queryKey:['admin-data',kind,id,auth.user?.id],queryFn:({signal})=>getRecord(kind,id!,auth.token,signal),enabled:Boolean(id&&id!=='nuevo')});
  async function saved(record:DataRecord){await qc.invalidateQueries({queryKey:['admin-data']});await qc.invalidateQueries({queryKey:['dashboard']});await qc.invalidateQueries({queryKey:['public-data']});await qc.invalidateQueries({queryKey:['public-search']});navigate(`/admin/datos/${kind}/${record.id}`);}
  return <section className={styles.page}><header className={styles.hero}><p>Administración de datos</p><h1>{DOMAINS[kind].title}</h1><p>Registra la fuente y el corte del dato. Una persona distinta del autor y del último editor debe aprobar su publicación.</p></header>
    <nav aria-label="Dominios de datos" className={styles.tabs}>{Object.entries(DOMAINS).map(([key,v])=><Link key={key} to={`/admin/datos/${key}`} aria-current={key===kind?'page':undefined}>{v.title}</Link>)}</nav>
    {id==='nuevo'?(auth.hasPermission('data:create')?<DataForm kind={kind} onSaved={saved}/>:<p>No tienes permiso de captura.</p>):id?(detail.isPending?<PageFeedback title="Cargando ficha" message="Consultando datos internos."/>:detail.isError?<PageFeedback title="Ficha no disponible" message="No fue posible consultar el registro."/>:<AdminRecord key={`${detail.data.id}-${detail.data.version}`} record={detail.data} onSaved={saved}/>):<>
      <div className={styles.actions}>{auth.hasPermission('data:create')&&<Link to={`/admin/datos/${kind}/nuevo`}>Crear registro</Link>}<Link to={DOMAINS[kind].path}>Ver módulo público</Link></div>
      <form className={styles.filters} onSubmit={e=>{e.preventDefault();const next=new URLSearchParams(params);if(search.trim())next.set('search',search.trim());else next.delete('search');next.delete('page');setParams(next);}}><label>Buscar<input value={search} onChange={e=>setSearch(e.target.value)} minLength={2}/></label><label>Estado<select value={params.get('status')??''} onChange={e=>{const next=new URLSearchParams(params);if(e.target.value)next.set('status',e.target.value);else next.delete('status');next.delete('page');setParams(next);}}><option value="">Todos</option>{Object.entries(STATUS).map(([code,label])=><option key={code} value={code}>{label}</option>)}</select></label><button>Buscar</button></form>
      {listing.isPending?<p>Cargando registros…</p>:listing.isError?<ErrorNotice error={listing.error}/>:<><div className={styles.table}><table><thead><tr><th>Título</th><th>Estado</th><th>Corte</th><th>Responsable</th></tr></thead><tbody>{listing.data.items.map(r=><tr key={r.id}><th><Link to={`/admin/datos/${kind}/${r.id}`}>{r.title}</Link></th><td>{STATUS[r.status!]}</td><td>{r.asOf}</td><td>{r.responsible}</td></tr>)}</tbody></table></div>{!listing.data.items.length&&<p>No hay registros para esta consulta.</p>}<div className={styles.actions}><button disabled={listing.data.pagination.page<=1} onClick={()=>{const next=new URLSearchParams(params);next.set('page',String(listing.data.pagination.page-1));setParams(next);}}>Anterior</button><span>Página {listing.data.pagination.page} · {listing.data.pagination.totalItems} registros</span><button disabled={listing.data.pagination.page>=listing.data.pagination.totalPages} onClick={()=>{const next=new URLSearchParams(params);next.set('page',String(listing.data.pagination.page+1));setParams(next);}}>Siguiente</button></div></>}
    </>}
  </section>;
}
function AdminRecord({record,onSaved}:{record:DataRecord;onSaved:(r:DataRecord)=>Promise<void>}){
  const auth=useAuth();const qc=useQueryClient();const [note,setNote]=useState('');
  const history=useQuery({queryKey:['data-history',record.id,record.version],queryFn:({signal})=>request<HistoryItem[]>(`/admin/data/${record.kind}/${record.id}/history`,auth.token,undefined,'GET',signal)});
  const mutation=useMutation({mutationFn:(action:string)=>request<DataRecord>(`/admin/data/${record.kind}/${record.id}/transitions`,auth.token,{version:record.version,action,note},'POST'),onSuccess:onSaved});
  return <><Link to={`/admin/datos/${record.kind}`}>← Volver al listado</Link><h2>{record.title} <span className={styles.badge}>{STATUS[record.status!]}</span></h2>
    {record.status==='DRAFT'&&auth.hasPermission('data:update')?<DataForm kind={record.kind} record={record} onSaved={onSaved}/>:<><EventPhoto record={record}/><p>{record.summary}</p><RecordDetails record={record}/><RecordMetadata record={record}/></>}
    <section className={styles.card}><h2>Revisión y publicación</h2><p>Los registros publicados son inmutables. Para corregirlos, archívalos y reábrelos: quedarán fuera de consulta pública hasta volver a publicarse.</p><label className={styles.field}>Nota para el historial (obligatoria al devolver)<textarea value={note} maxLength={2000} onChange={e=>setNote(e.target.value)}/></label><div className={styles.actions}>{actions.filter(([, ,status,permission])=>status===record.status&&auth.hasPermission(permission)).map(([action,label])=><button key={action} disabled={mutation.isPending||(action==='REJECT'&&!note.trim())||(action==='APPROVE'&&[record.createdBy,record.editedBy].includes(auth.user?.id))} onClick={()=>mutation.mutate(action)}>{label}</button>)}<button onClick={()=>void qc.invalidateQueries({queryKey:['admin-data']})}>Recargar ficha</button></div><ErrorNotice error={mutation.error}/></section>
    <section><h2>Historial</h2>{history.isError?<ErrorNotice error={history.error}/>:<ol className={styles.history}>{history.data?.map(h=><li key={h.id}>{new Date(h.createdAt).toLocaleString('es-MX')} · {actions.find(([code])=>code===h.action)?.[1]??({CREATE:'Creación',UPDATE:'Edición',IMPORT_HISTORICAL:'Importación histórica'}[h.action]??h.action)} · {h.actor??'Carga histórica'}{h.note&&`: ${h.note}`}</li>)}</ol>}</section>
  </>;
}
function localDateTime(value:string){const date=new Date(value);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);}
function DataForm({kind,record,onSaved}:{kind:Domain;record?:DataRecord;onSaved:(r:DataRecord)=>Promise<void>}){
  const auth=useAuth();const [relations,setRelations]=useState({mediaIds:record?.mediaIds??[],signalIds:record?.signalIds??[],trendIds:record?.trendIds??[]});const [showMedia,setShowMedia]=useState(false);
  const [showPhoto,setShowPhoto]=useState(false);
  const [photo,setPhoto]=useState(record?.photo??null);
  const [photoId,setPhotoId]=useState<number|null>(record?.details.photo_media_id?Number(record.details.photo_media_id):null);
  const [values,setValues]=useState<Record<string,string>>(()=>{
    const base:Record<string,string>={title:record?.title??'',summary:record?.summary??'',sourceName:record?.sourceName??'',sourceUrl:record?.sourceUrl??'',asOf:record?.asOf??new Date().toISOString().slice(0,10),responsible:record?.responsible??`${auth.user?.firstName??''} ${auth.user?.lastName??''}`.trim(),validFrom:record?.validFrom??'',validUntil:record?.validUntil??'',tags:record?.tags.join(', ')??''};
    DOMAINS[kind].fields.forEach(f=>{const v=record?.details[f.key];base[f.key]=v==null?(f.options?.[0][0]??(f.key==='currency'?'USD':'')):f.type==='datetime-local'?localDateTime(String(v)):String(v);});return base;
  });
  const [relationSearch,setRelationSearch]=useState('');const suffix=relationSearch.trim().length>=2?`&search=${encodeURIComponent(relationSearch.trim())}`:'';
  const signals=useQuery({queryKey:['relation-signals',suffix],queryFn:({signal})=>request<Page<{id:number;title:string}>>(`/signals?pageSize=100${suffix}`,null,undefined,'GET',signal)});
  const trends=useQuery({queryKey:['relation-trends',suffix],queryFn:({signal})=>request<Page<{id:number;title:string}>>(`/trends?pageSize=100${suffix}`,null,undefined,'GET',signal)});
  const mutation=useMutation({mutationFn:(input:RecordInput)=>request<DataRecord>(`/admin/data/${kind}${record?`/${record.id}`:''}`,auth.token,{...input,...(record?{version:record.version}:{})},record?'PUT':'POST'),onSuccess:onSaved});
  function submit(e:FormEvent){e.preventDefault();const details:Record<string,string|number|null>={};DOMAINS[kind].fields.forEach(f=>{const v=values[f.key].trim();details[f.key]=!v&&f.optional?null:f.type==='number'?Number(v):f.type==='datetime-local'?new Date(v).toISOString():v;});if(kind==='events')details.photo_media_id=photoId;mutation.mutate({title:values.title,summary:values.summary,sourceName:values.sourceName,sourceUrl:values.sourceUrl||null,asOf:values.asOf,responsible:values.responsible,validFrom:values.validFrom||null,validUntil:values.validUntil||null,tags:values.tags.split(',').map(v=>v.trim()).filter(Boolean),details,...relations});}
  const set=(key:string,value:string)=>setValues(v=>({...v,[key]:value}));
  return <><form className={styles.form} onSubmit={submit}><fieldset><legend>Identificación y trazabilidad</legend><div className={styles.fields}>{[
    ['title','Título','text'],['summary','Descripción','textarea'],['sourceName','Fuente o referencia bibliográfica','text'],['sourceUrl','Enlace de la fuente (opcional)','url'],['asOf','Fecha de corte','date'],['responsible','Responsable del dato','text'],['validFrom','Visible desde (opcional)','date'],['validUntil','Visible hasta (opcional)','date'],['tags','Etiquetas separadas por comas (opcional)','text']
  ].map(([key,label,type])=><label className={`${styles.field} ${type==='textarea'?styles.wide:''}`} key={key}>{label}{type==='textarea'?<textarea value={values[key]} onChange={e=>set(key,e.target.value)} required maxLength={10000}/>:<input type={type} value={values[key]} onChange={e=>set(key,e.target.value)} required={!['sourceUrl','validFrom','validUntil','tags'].includes(key)} maxLength={key==='sourceUrl'?2000:key==='sourceName'?300:200}/>}</label>)}</div></fieldset>
    <fieldset><legend>{DOMAINS[kind].title}</legend><div className={styles.fields}>{DOMAINS[kind].fields.map(f=><label className={`${styles.field} ${f.type==='textarea'?styles.wide:''}`} key={f.key}>{f.label}{f.options?<select value={values[f.key]} onChange={e=>set(f.key,e.target.value)}>{f.options.map(([code,label])=><option key={code} value={code}>{label}</option>)}</select>:f.type==='textarea'?<textarea required={!f.optional} value={values[f.key]} onChange={e=>set(f.key,e.target.value)} maxLength={10000}/>:<input type={f.type??'text'} required={!f.optional} step={f.type==='number'?'any':undefined} value={values[f.key]} onChange={e=>set(f.key,e.target.value)} maxLength={f.type==='url'?2000:200}/>}</label>)}</div></fieldset>
    {kind==='events'&&<fieldset><legend>Foto del evento (opcional)</legend><p>Selecciona una imagen pública o súbela desde la biblioteca.</p>{photo&&<img className={styles.eventPhoto} src={photo.url} alt={photo.altText}/>}<div className={styles.actions}>{auth.hasPermission('media:read-internal')&&<button type="button" onClick={()=>setShowPhoto(v=>!v)}>{showPhoto?'Cerrar selección de foto':photoId?'Cambiar foto':'Escoger foto'}</button>}{photoId&&<button type="button" onClick={()=>{setPhoto(null);setPhotoId(null);}}>Quitar foto</button>}</div>{photoId&&!photo&&<p>La foto seleccionada ya no está disponible públicamente. Selecciona otra o quítala.</p>}</fieldset>}
    <fieldset><legend>Evidencia y archivos</legend><label className={styles.field}>Buscar señales y tendencias publicadas<input value={relationSearch} onChange={e=>setRelationSearch(e.target.value)}/></label><div className={styles.fields}>{([['signalIds','Señales',signals.data?.items??[]],['trendIds','Tendencias',trends.data?.items??[]]] as const).map(([key,label,items])=><div key={key}><label className={styles.field}>{label}<select value="" onChange={e=>{const id=Number(e.target.value);if(id)setRelations(v=>({...v,[key]:[...new Set([...v[key],id])]}));}}><option value="">Selecciona para asociar</option>{items.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><ul>{relations[key].map(id=><li key={id}>{items.find(i=>i.id===id)?.title??`${label} #${id}`} <button type="button" onClick={()=>setRelations(v=>({...v,[key]:v[key].filter(n=>n!==id)}))}>Quitar</button></li>)}</ul></div>)}</div>{(signals.isError||trends.isError)&&<p role="alert">No se pudieron cargar las opciones de evidencia. Las relaciones existentes se conservan.</p>}
      <ul>{relations.mediaIds.map(id=><li key={id}>Archivo #{id} <button type="button" onClick={()=>setRelations(v=>({...v,mediaIds:v.mediaIds.filter(n=>n!==id)}))}>Quitar</button></li>)}</ul>{auth.hasPermission('media:read-internal')&&<><button type="button" onClick={()=>setShowMedia(v=>!v)}>{showMedia?'Cerrar biblioteca':'Asociar archivo de la biblioteca'}</button></>}
    </fieldset><ErrorNotice error={mutation.error}/><div className={styles.actions}><button disabled={mutation.isPending} type="submit">{mutation.isPending?'Guardando…':'Guardar borrador'}</button><Link to={`/admin/datos/${kind}`}>Volver al listado</Link></div>
  </form>{showPhoto&&<MediaLibrary kind="image" compact onSelect={asset=>{setPhoto({id:asset.id,url:asset.url!,altText:asset.altText||asset.title||'Foto del evento'});setPhotoId(asset.id);setShowPhoto(false);}}/>}{showMedia&&<MediaLibrary compact onSelect={asset=>{setRelations(v=>({...v,mediaIds:[...new Set([...v.mediaIds,asset.id])]}));setShowMedia(false);}}/>}</>;
}
