import { type FormEvent, type ReactNode, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import styles from "./ObservatoryModulePage.module.css";

type PageKind = "dashboard" | "industry" | "indicators" | "ecosystem" | "value-chain" | "investments" | "events" | "resources" | "search";

const resourceLinks = [
  { label: "INEGI - Producto Interno Bruto", href: "https://www.inegi.org.mx/app/tabulados/default.html?nc=588" },
  { label: "Data México - Querétaro", href: "https://www.economia.gob.mx/datamexico/es/profile/geo/queretaro-qt" },
  { label: "Secretaría de Economía - Plan Maestro de Semiconductores", href: "https://www.gob.mx/se/prensa/preside-marcelo-ebrard-reunion-de-seguimiento-del-plan-maestro-de-semiconductores-2024-2030" }
];

const dataByYear = {
  "2025": { range: [650, 780], label: "SAM estimado", note: "Estimación del estudio mediante tres proxies; no es venta observada.", points: [650, 780] },
  "2030": { range: [869, 1044], label: "SAM proyectado", note: "Escenario base del informe, condicionado a capacidades, inversión e infraestructura.", points: [869, 1044] }
} as const;

function DashboardPage() {
  const [year, setYear] = useState<keyof typeof dataByYear>("2025");
  const data = dataByYear[year];
  const max = 1100;
  const barWidth = (value: number) => `${(value / max) * 100}%`;
  return <PageFrame eyebrow="Lectura rápida" title="Dashboard ejecutivo" lead="Una síntesis inicial de la pertinencia de la industria de semiconductores en Querétaro. Las cifras son línea base del estudio y se actualizarán cuando exista el servicio de datos.">
    <div className={styles.dashboardControls} role="group" aria-label="Horizonte de la estimación"><span>Horizonte</span>{(["2025", "2030"] as const).map((option) => <button className={year === option ? styles.selected : ""} key={option} onClick={() => setYear(option)} type="button">{option}</button>)}</div>
    <section className={styles.metrics} aria-label="Indicadores ejecutivos"><article><span>Mercado atendible</span><strong>US${data.range[0]}–{data.range[1]} M</strong><p>{data.label}</p></article><article><span>Dimensiones SIIP</span><strong>5</strong><p>económica, tecnológica, social, normativa y sostenible</p></article><article><span>Sectores tractores</span><strong>3</strong><p>automotriz, aeroespacial y centros de datos</p></article></section>
    <section className={styles.chartPanel} aria-labelledby="sam-title"><div><p className={styles.eyebrow}>Mercado atendible</p><h2 id="sam-title">Rango estimado, millones de USD</h2><p>{data.note}</p></div><div className={styles.rangeChart} role="img" aria-label={`Mercado atendible ${year}: entre ${data.range[0]} y ${data.range[1]} millones de dólares`}><span style={{ width: barWidth(data.range[0]) }}><b>US${data.range[0]} M</b></span><span className={styles.rangeHigh} style={{ width: barWidth(data.range[1]) }}><b>US${data.range[1]} M</b></span><div aria-hidden="true"><i>0</i><i>550</i><i>1,100</i></div></div></section>
    <section><div className={styles.sectionHeader}><p className={styles.eyebrow}>Lectura de pertinencia</p><h2>Fortalezas que deben convertirse en capacidad sostenida</h2></div><div className={styles.grid}><article className={styles.card}><strong>Alta: económica y tecnológica</strong><p>La demanda sectorial, la manufactura avanzada y capacidades de ingeniería favorecen la inserción regional.</p></article><article className={styles.card}><strong>Moderada: social</strong><p>La formación especializada es emergente; persisten brechas de matemáticas, TIC profesionales e inglés técnico.</p></article><article className={styles.card}><strong>En desarrollo: normativa y sostenible</strong><p>La infraestructura energética, regulación y gestión de impactos deben acompañar el crecimiento.</p></article></div></section>
  </PageFrame>;
}

function IndustryPage() { return <PageFrame eyebrow="Contexto sectorial" title="Industria de semiconductores" lead="Los semiconductores son componentes esenciales de la economía digital: habilitan cómputo, comunicaciones, movilidad, automatización y sistemas críticos."><section className={styles.explainer}><div><p className={styles.eyebrow}>Cómo funcionan</p><h2>Controlan el paso de la electricidad</h2><p>Materiales como el silicio pueden comportarse como aislantes o conductores según su estructura y el dopaje controlado con pequeñas cantidades de otros elementos. Esa propiedad permite crear transistores: interruptores microscópicos que representan, procesan y almacenan información.</p><p>Miles de millones de transistores conectados forman un circuito integrado. Dependiendo de su diseño, un chip puede calcular, guardar datos, administrar energía, convertir señales o comunicar dispositivos.</p></div><div className={styles.grid}><article className={styles.card}><strong>Procesadores</strong><p>Ejecutan instrucciones en computadoras, teléfonos y servidores.</p></article><article className={styles.card}><strong>Memorias</strong><p>Almacenan temporal o permanentemente datos y programas.</p></article><article className={styles.card}><strong>Analógicos y potencia</strong><p>Gestionan señales, sensores, energía y conversión eléctrica.</p></article></div></section><section className={styles.flow}><article><b>01</b><strong>Diseño</strong><p>Arquitectura, propiedad intelectual, circuitos y verificación.</p></article><article><b>02</b><strong>Fabricación</strong><p>Procesos de oblea, litografía y control de alta precisión.</p></article><article><b>03</b><strong>Ensamble y prueba</strong><p>Empaquetado, validación y confiabilidad.</p></article><article><b>04</b><strong>Integración</strong><p>Aplicación en sistemas, productos y servicios.</p></article></section><section className={styles.twoColumns}><div><p className={styles.eyebrow}>Panorama global</p><h2>Una industria estratégica y altamente especializada</h2><p>La demanda mundial se concentra en inteligencia artificial, infraestructura de cómputo, comunicaciones, automoción y electrónica industrial. Su cadena combina empresas de diseño, fabricantes de obleas, proveedores de equipos, ensambladores y desarrolladores de productos finales.</p><p>Entre las compañías líderes se encuentran NVIDIA, Intel, Qualcomm, Broadcom, AMD, Samsung Electronics, SK hynix, TSMC, Micron y Texas Instruments. ASML, Applied Materials, Lam Research y KLA son referencias en equipo y procesos para fabricación.</p></div><aside className={styles.callout}><strong>Oportunidad regional</strong><p>La inserción no empieza necesariamente en una fábrica de frontera. Querétaro puede fortalecer diseño, ingeniería, integración electrónica, pruebas, talento y proveeduría, articulados con su manufactura avanzada.</p></aside></section></PageFrame>; }

function IndicatorsPage() { const rows = [["Económica", "Demanda, inversión, empleo y encadenamientos"], ["Tecnológica", "I+D, diseño, laboratorios y capacidades productivas"], ["Social", "Talento, formación, inclusión y vinculación"], ["Normativa", "Política, regulación y gobernanza"], ["Sostenible", "Energía, agua, emisiones y gestión ambiental"]]; return <PageFrame eyebrow="Sistema Integral de Indicadores de Pertinencia" title="Indicadores de pertinencia" lead="El SIIP propuesto por el informe permite observar la pertinencia como un sistema: no sólo cuánto crece el sector, sino si el territorio está preparado para sostenerlo."><div className={styles.tableWrap}><table><thead><tr><th>Dimensión</th><th>Qué se observa</th><th>Estado inicial</th></tr></thead><tbody>{rows.map(([name, focus]) => <tr key={name}><td><strong>{name}</strong></td><td>{focus}</td><td>{name === "Económica" || name === "Tecnológica" ? "Alta" : name === "Social" ? "Moderada" : "En desarrollo"}</td></tr>)}</tbody></table></div><section className={styles.callout}><strong>Uso responsable</strong><p>Estos indicadores son un marco de seguimiento, no un índice único. Cada cifra deberá publicarse con definición, fórmula, fuente, periodo y responsable de actualización.</p></section></PageFrame>; }

function EcosystemPage() { const actors = [["Empresas", "Diseño, integración electrónica, manufactura avanzada, pruebas y proveedores especializados."], ["Academia", "El TecNM Querétaro ofrece Ingeniería en Semiconductores y Maestría en Semiconductores; se suman UTEQ, UPQ, UNAQ y otras instituciones que forman talento técnico y de ingeniería."], ["Investigación", "CIDESI, CENAM y laboratorios regionales aportan I+D, metrología, caracterización y validación."], ["Gobierno y clústeres", "Articulan inversión, infraestructura, formación, vinculación y la creación de condiciones para nuevos proyectos."]]; return <PageFrame eyebrow="Capacidades conectadas" title="Ecosistema regional" lead="La competitividad regional surge de la colaboración entre empresas, academia, centros de investigación y gobierno; no de un solo actor."><div className={styles.grid}>{actors.map(([name, description]) => <article className={styles.card} key={name}><strong>{name}</strong><p>{description}</p></article>)}</div><section className={styles.twoColumns}><div><p className={styles.eyebrow}>Formación especializada</p><h2>Talento desde el aula hasta el posgrado</h2><p>El TecNM Campus Querétaro cuenta con programas enfocados específicamente en semiconductores: Ingeniería en Semiconductores y Maestría en Semiconductores. Estos programas permiten desarrollar capacidades en electrónica, diseño, materiales, manufactura y aplicaciones industriales.</p><a className={styles.actionLink} href="https://queretaro.tecnm.mx/" rel="noreferrer" target="_blank">Conocer la oferta del TecNM Querétaro →</a></div><aside className={styles.callout}><strong>Impulso nacional</strong><p>En México se impulsa una agenda para fortalecer diseño, formación de talento, investigación aplicada, inversión y cadenas de proveeduría. El Plan Maestro de Semiconductores 2024-2030, los foros de colaboración con industria y academia, y el desarrollo de capacidades de diseño buscan conectar al país con eslabones de mayor valor agregado.</p></aside></section><section className={styles.callout}><strong>Prioridad de consolidación</strong><p>Convertir la oferta de talento y las capacidades de investigación en proyectos recurrentes con empresas, formación práctica, estancias y rutas de especialización vinculadas a la cadena de valor.</p></section></PageFrame>; }

function ValueChainPage() { return <PageFrame eyebrow="De conocimiento a producto" title="Cadena de valor" lead="La industria conecta actividades intensivas en conocimiento, equipo especializado y manufactura. Cada eslabón requiere capacidades y proveedores distintos."><section className={styles.chain}><article><b>1</b><strong>Investigación y materiales</strong><p>Se desarrollan materiales semiconductores, procesos, sensores y métodos de caracterización. Universidades y centros de investigación generan conocimiento, prototipos y propiedad intelectual.</p></article><article><b>2</b><strong>Diseño e IP</strong><p>Se define qué debe hacer el chip, su arquitectura, circuitos, simulación y verificación. El diseño utiliza propiedad intelectual reutilizable y herramientas EDA para comprobar el comportamiento antes de fabricar.</p></article><article><b>3</b><strong>Fabricación</strong><p>Una foundry transforma obleas de silicio mediante deposición de capas, litografía, grabado, implantación y metrología. Es el eslabón de mayor intensidad de capital, agua ultrapura, energía y equipo especializado.</p></article><article><b>4</b><strong>Empaque y prueba</strong><p>El dado se corta, encapsula, conecta y prueba para protegerlo y asegurar desempeño. El empaque avanzado puede unir varios chips y es clave para rendimiento, consumo y confiabilidad.</p></article><article><b>5</b><strong>Integración y mercado</strong><p>Los semiconductores se integran en tarjetas electrónicas, módulos y sistemas. Automotriz, aeroespacial, salud, telecomunicaciones, industria y centros de datos traducen el chip en productos y servicios.</p></article></section><section className={styles.twoColumns}><div><h2>Ruta viable para Querétaro</h2><p>El informe identifica oportunidades especialmente en diseño, integración electrónica, empaquetado y pruebas, ingeniería y aplicaciones sectoriales, apalancadas por automotriz, aeroespacial y centros de datos.</p><p>También son relevantes los servicios transversales: metrología, certificación, software, mantenimiento de equipo, logística especializada y formación de talento.</p></div><Link className={styles.actionLink} to="/inversiones">Ver inversiones y expansión →</Link></section></PageFrame>; }

function InvestmentsPage() { return <PageFrame eyebrow="Capacidad instalada y anunciada" title="Inversiones y expansión" lead="Este módulo distingue proyectos anunciados de operaciones verificadas. Su propósito es dar seguimiento, no anticipar resultados."><div className={styles.grid}><article className={styles.card}><strong>QSM Semiconductores</strong><p>La empresa reportó centros de ingeniería y diseño en Querétaro, junto con un proyecto de manufactura. En febrero de 2026, la Secretaría de Economía informó que la planta estaba avanzada y que la producción podría iniciar hacia el final del año.</p><a href="https://www.gob.mx/se/prensa/atencion-a-medios-del-secretario-de-economia-marcelo-ebrard-al-termino-de-la-1-sesion-ordinaria-del-comite-promotor-de-inversiones?idiom=es" rel="noreferrer" target="_blank">Ver comunicado oficial</a></article><article className={styles.card}><strong>Infraestructura digital</strong><p>CloudHQ anunció una inversión de US$4,800 M para seis centros de datos en Querétaro; AWS anunció US$5,000 M para una región digital. Son proyectos que elevan la demanda de infraestructura y talento digital.</p><a href="https://www.gob.mx/presidencia/prensa/plan-mexico-avanza-se-anuncia-inversion-de-4-mil-800-mdd-de-cloudhq-para-la-construccion-de-6-centros-de-datos-en-queretaro" rel="noreferrer" target="_blank">Ver anuncio de CloudHQ</a></article></div><section className={styles.callout}><strong>Regla editorial</strong><p>Cada ficha futura deberá incluir monto, fecha, estado, fuente primaria, ubicación general, empleos anunciados y última verificación. El observatorio no validará una inversión sólo por una nota de prensa secundaria.</p></section></PageFrame>; }

function EventsPage() { return <PageFrame eyebrow="Agenda del ecosistema" title="Eventos y convocatorias" lead="Próximamente, este espacio concentrará oportunidades verificadas de formación, vinculación, financiamiento y difusión."><section className={styles.empty}><strong>Agenda en preparación</strong><p>Mientras se integra un calendario administrable, consulta las convocatorias vigentes directamente con las instituciones organizadoras. Las fechas deben verificarse antes de cualquier registro.</p><div><a href="https://queretaro.tecnm.mx/" rel="noreferrer" target="_blank">Instituto Tecnológico de Querétaro</a><a href="https://www.gob.mx/se" rel="noreferrer" target="_blank">Secretaría de Economía</a></div></section></PageFrame>; }

function ResourcesPage() { return <PageFrame eyebrow="Fuentes para profundizar" title="Recursos y bases de datos" lead="Accesos iniciales a fuentes institucionales útiles para investigar, contrastar datos y dar seguimiento al sector."><div className={styles.grid}>{resourceLinks.map((source) => <a className={styles.resource} href={source.href} key={source.href} rel="noreferrer" target="_blank"><strong>{source.label}</strong><span>Consulta la fuente →</span></a>)}<a className={styles.resource} href="https://www.semiconductors.org/policies/tax/market-data/" rel="noreferrer" target="_blank"><strong>Semiconductor Industry Association - Market Data</strong><span>Consulta la fuente →</span></a></div><section className={styles.callout}><strong>Antes de reutilizar un dato</strong><p>Registra fuente, definición, unidad y cobertura geográfica. Las estimaciones de mercado no son equivalentes a estadísticas oficiales.</p></section></PageFrame>; }

function SearchPage() { const [query, setQuery] = useState(""); const navigate = useNavigate(); const submit = (event: FormEvent) => { event.preventDefault(); const value = query.trim(); if (value.length >= 2) navigate(`/contenido?search=${encodeURIComponent(value)}`); }; return <PageFrame eyebrow="Consulta transversal" title="Buscador inteligente" lead="Encuentra publicaciones, noticias, señales, tendencias y alertas. Esta primera versión reutiliza el índice público ya disponible; la búsqueda unificada llegará con la Fase 4."><form className={styles.searchForm} onSubmit={submit}><label htmlFor="search">¿Qué tema quieres explorar?</label><div><input id="search" minLength={2} onChange={(event) => setQuery(event.target.value)} placeholder="Ej. empaquetado avanzado, talento, centros de datos" value={query} /><button type="submit">Buscar</button></div><small>Escribe al menos dos caracteres. La búsqueda actual consulta el contenido editorial publicado.</small></form><div className={styles.grid}><Link className={styles.resource} to="/senales"><strong>Señales</strong><span>Hechos verificados →</span></Link><Link className={styles.resource} to="/tendencias"><strong>Tendencias</strong><span>Patrones en evolución →</span></Link><Link className={styles.resource} to="/alertas"><strong>Alertas</strong><span>Oportunidades y riesgos →</span></Link></div></PageFrame>; }

function PageFrame({ eyebrow, title, lead, children }: { eyebrow: string; title: string; lead: string; children: ReactNode }) { return <div className={styles.page}><header className={styles.hero}><p>{eyebrow}</p><h1>{title}</h1><span>{lead}</span></header>{children}</div>; }

export function ObservatoryModulePage({ kind }: { kind: PageKind }) { switch (kind) { case "dashboard": return <DashboardPage />; case "industry": return <IndustryPage />; case "indicators": return <IndicatorsPage />; case "ecosystem": return <EcosystemPage />; case "value-chain": return <ValueChainPage />; case "investments": return <InvestmentsPage />; case "events": return <EventsPage />; case "resources": return <ResourcesPage />; case "search": return <SearchPage />; } }
