import { Link } from "react-router-dom";
import styles from "./InformationPage.module.css";

const FCVS = ["Tecnología", "Mercado", "Inversión", "Talento", "Regulación", "Manufactura", "Cadena de suministro", "Sostenibilidad", "Propiedad intelectual"];

export function SurveillancePage() {
  return <div className={styles.page}>
    <header className={styles.hero}><p className={styles.eyebrow}>De la evidencia a la acción</p><h1>Vigilancia tecnológica</h1><p>Observamos, validamos y relacionamos información del sector para detectar cambios relevantes antes de que pierdan valor estratégico.</p></header>
    <section id="proceso"><div className={styles.sectionHeader}><p className={styles.eyebrow}>Proceso</p><h2>Cómo se construye el conocimiento</h2><p>Una noticia puede iniciar una investigación, pero sólo se convierte en señal cuando cumple los criterios de relevancia, actualidad, veracidad, trazabilidad y clasificación.</p></div><ol className={styles.flow}><li><strong>Fuentes</strong><span>Documentos y evidencia localizable</span></li><li><strong>Señales</strong><span>Cambios verificados y contextualizados</span></li><li><strong>Tendencias</strong><span>Patrones sostenidos entre señales</span></li><li><strong>Alertas</strong><span>Riesgos u oportunidades que requieren atención</span></li><li><strong>Productos</strong><span>Boletines, informes y visualizaciones</span></li></ol></section>
    <section aria-label="Explora la vigilancia tecnológica"><div className={styles.sectionHeader}><p className={styles.eyebrow}>Productos de vigilancia</p><h2>Cada nivel responde una pregunta distinta</h2></div><div className={styles.grid}><article className={styles.card}><strong>¿Qué está cambiando?</strong><p>Las señales documentan hechos verificables, vinculados con una fuente y un factor crítico.</p><Link to="/senales">Señales →</Link></article><article className={styles.card}><strong>¿Se está formando un patrón?</strong><p>Las tendencias conectan señales coherentes y muestran dirección, madurez y evidencia acumulada.</p><Link to="/tendencias">Tendencias →</Link></article><article className={styles.card}><strong>¿Qué requiere atención?</strong><p>Las alertas comunican riesgos u oportunidades con plazo, audiencias y recomendaciones.</p><Link to="/alertas">Alertas →</Link></article></div></section>
    <section id="factores"><div className={styles.sectionHeader}><p className={styles.eyebrow}>Alcance temático</p><h2>Nueve Factores Críticos de Vigilancia</h2><p>Los FCV mantienen la observación alineada con las necesidades estratégicas del ecosistema.</p></div><div className={styles.grid}>{FCVS.map((fcv, index) => <article className={styles.card} key={fcv}><strong>{String(index + 1).padStart(2, "0")} · {fcv}</strong></article>)}</div></section>
    <section id="metodologia"><div className={styles.sectionHeader}><p className={styles.eyebrow}>Metodología</p><h2>Reglas transparentes, interpretación humana</h2></div><div className={styles.grid}><article className={styles.card}><strong>Prioridad de señales</strong><p>El IPS multiplica impacto, urgencia y confiabilidad. El resultado va de 1 a 27 y ayuda a priorizar el seguimiento.</p></article><article className={styles.card}><strong>Madurez de tendencias</strong><p>Una tendencia necesita señales validadas, coherencia de dirección, diversidad de fuentes y una ventana temporal suficiente.</p></article><article className={styles.card}><strong>Nivel de alertas</strong><p>Amarillo indica seguimiento, naranja respuesta próxima y rojo comunicación urgente. El color no equivale al IPS de una señal.</p></article></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Madurez</th><th>Señales mínimas</th><th>Ventana</th><th>Fuentes</th></tr></thead><tbody><tr><td>Emergente</td><td>3</td><td>6 meses</td><td>2</td></tr><tr><td>En consolidación</td><td>5</td><td>12 meses</td><td>3</td></tr><tr><td>Consolidada</td><td>8</td><td>24 meses</td><td>5</td></tr></tbody></table></div></section>
    </div>;
}
