import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useForm, useWatch } from "react-hook-form";
import { Link, useNavigate, useParams } from "react-router-dom";
import { isApiError } from "@/api";
import { Button } from "@/components/ui/Button";
import { PageFeedback } from "@/components/feedback/PageFeedback";
import { FieldHelp, FieldLabel } from "@/components/forms/FieldHelp";
import { useAuth } from "@/features/auth/AuthContext";
import { applyZodErrors } from "@/features/auth/form-errors";
import { getAdminEntity } from "../admin.service";
import { createAlert,getAlertFormOptions,linkAlertAudiences,linkAlertIds,unlinkAlertRelation,updateAlert } from "./alert-form.service";
import { alertFormSchema,alertReadiness,toAlertInput,type AlertFormValues } from "./alert-form.schema";
import type { Alert,AlertFormOptions,Option } from "./alert-form.types";
import {AssessmentField} from "@/features/assessment/AssessmentField";
import type {AlertAssessment} from "@/features/assessment/assessment";
import styles from "../signals/SignalForm.module.css";

const EMPTY:AlertFormValues={title:"",executiveSummary:"",implications:"",recommendations:"",responseDeadline:"",assessment:null,activationRule:"",notes:"",signalIds:[],trendIds:[],audienceCodes:[]};
const valuesFrom=(a:Alert):AlertFormValues=>({title:a.title,executiveSummary:a.executiveSummary,implications:a.implications??"",recommendations:a.recommendations??"",responseDeadline:a.responseDeadline??"",assessment:a.assessment??null,activationRule:a.activationRule??"",notes:a.notes??"",signalIds:a.signals.map((v)=>String(v.id)),trendIds:a.trends.map((v)=>String(v.id)),audienceCodes:a.audiences.map((v)=>v.code)});
const mergeCurrent=(options:Option[],items:Array<{id:number;businessCode:string;title:string;statusCode:string}>):Option[]=>{const map=new Map(options.map((v)=>[v.value,v]));items.forEach((v)=>{if(!map.has(String(v.id)))map.set(String(v.id),{value:String(v.id),label:`${v.businessCode} · ${v.title} · ${v.statusCode}`})});return [...map.values()]};

function Checks({label,name,options,register,disabled}:{label:string;name:"signalIds"|"trendIds"|"audienceCodes";options:Option[];register:ReturnType<typeof useForm<AlertFormValues>>["register"];disabled?:boolean}){return <fieldset className={`${styles.field} ${styles.wide}`} disabled={disabled}><legend>{label} <FieldHelp>{name === "audienceCodes" ? "Elige públicos con capacidad de actuar; el lenguaje y canal deben adecuarse a ellos." : "Vincula evidencia que sustente la activación. Sólo se admite evidencia metodológicamente elegible."}</FieldHelp></legend>{options.length===0?<p>No hay opciones disponibles.</p>:options.map((v)=><label key={v.value}><input type="checkbox" value={v.value} {...register(name)}/> {v.label}</label>)}</fieldset>}

function AlertForm({initial,mode,options,alert}:{initial:AlertFormValues;mode:"create"|"edit";options:AlertFormOptions;alert?:Alert}){
  const auth=useAuth();const navigate=useNavigate();const queryClient=useQueryClient();const form=useForm<AlertFormValues>({defaultValues:initial});const {register,handleSubmit,setError,control,formState:{errors}}=form;const watched=useWatch({control}) as AlertFormValues;const readiness=alertReadiness({...initial,...watched});
  const mutation=useMutation({mutationFn:async(values:AlertFormValues)=>{const input=toAlertInput(values);if(mode==="create")return createAlert(input,auth.token!);const current=alert!;const canLink=auth.hasPermission("alerts:link-evidence");if(canLink){const syncIds=async(relation:"signals"|"trends",oldIds:number[],newIds:number[])=>{const add=newIds.filter((id)=>!oldIds.includes(id));const remove=oldIds.filter((id)=>!newIds.includes(id));await linkAlertIds(current.id,relation,add,auth.token!);for(const id of remove)await unlinkAlertRelation(current.id,relation,id,auth.token!)};await syncIds("signals",current.signals.map((v)=>Number(v.id)),input.signalIds);await syncIds("trends",current.trends.map((v)=>Number(v.id)),input.trendIds);const oldAudiences=current.audiences.map((v)=>v.code);await linkAlertAudiences(current.id,input.audienceCodes.filter((code)=>!oldAudiences.includes(code)),auth.token!);for(const code of oldAudiences.filter((code)=>!input.audienceCodes.includes(code)))await unlinkAlertRelation(current.id,"audiences",code,auth.token!)}const scalar={title:input.title,executiveSummary:input.executiveSummary,implications:input.implications,recommendations:input.recommendations,responseDeadline:input.responseDeadline,assessment:input.assessment,activationRule:input.activationRule,notes:input.notes};return updateAlert(current.id,{...scalar,updatedAt:current.updatedAt},auth.token!)} });
  const submit=handleSubmit(async(values)=>{const valid=alertFormSchema.safeParse(values);if(!valid.success){applyZodErrors(valid.error,setError);return}try{const response=await mutation.mutateAsync(valid.data);await Promise.all([queryClient.invalidateQueries({queryKey:["admin-entities","alerts"]}),queryClient.invalidateQueries({queryKey:["admin-entity","alerts",response.data.id]})]);navigate(`/admin/alertas/${response.data.id}`)}catch{/* rendered */}});const apiError=mutation.error&&isApiError(mutation.error)?mutation.error:null;
  return <form className={styles.form} noValidate onSubmit={submit}>{mutation.isError&&<div className={styles.summary} role="alert">{apiError?.status===409?"La alerta cambió en otra sesión. Recarga la versión actual antes de guardar.":apiError?.message??"No fue posible guardar la alerta."}</div>}
    <section className={styles.section}><h2>Resumen y respuesta</h2><div className={styles.grid}><div className={`${styles.field} ${styles.wide}`}><FieldLabel help="Nombra el riesgo u oportunidad y la decisión que requiere atención; máximo 150 caracteres." htmlFor="alert-title">Título</FieldLabel><input id="alert-title" maxLength={150} {...register("title")}/>{errors.title&&<small className={styles.error}>{errors.title.message}</small>}</div><div className={`${styles.field} ${styles.wide}`}><FieldLabel help="Síntesis ejecutiva de la situación, evidencia y relevancia. Se recomienda no exceder 300 palabras." htmlFor="alert-summary">Resumen ejecutivo</FieldLabel><textarea id="alert-summary" maxLength={10000} rows={7} {...register("executiveSummary")}/>{errors.executiveSummary&&<small className={styles.error}>{errors.executiveSummary.message}</small>}</div><div className={`${styles.field} ${styles.wide}`}><FieldLabel help="Explica efectos concretos para Querétaro, México y las audiencias seleccionadas." htmlFor="alert-implications">Implicaciones</FieldLabel><textarea id="alert-implications" maxLength={10000} rows={5} {...register("implications")}/></div><div className={`${styles.field} ${styles.wide}`}><FieldLabel help="Incluye al menos una acción concreta, viable y vinculada con el horizonte de respuesta." htmlFor="alert-recommendations">Recomendaciones</FieldLabel><textarea id="alert-recommendations" maxLength={10000} rows={5} {...register("recommendations")}/></div></div></section>
    <section className={styles.section}><h2>Activación</h2><div className={styles.grid}><div className={styles.field}><FieldLabel help="Último día útil para actuar: rojo suele ser menor de 15 días, naranja 15–30 y amarillo 30–90." htmlFor="alert-deadline">Fecha límite de respuesta</FieldLabel><input id="alert-deadline" type="date" {...register("responseDeadline")}/></div><div className={`${styles.field} ${styles.wide}`}><FieldLabel help="Documenta la ruta: señal con impacto y urgencia altos, o tendencia elegible con impacto estratégico alto." htmlFor="alert-rule">Regla de activación</FieldLabel><textarea id="alert-rule" maxLength={5000} rows={4} {...register("activationRule")}/></div><div className={`${styles.field} ${styles.wide}`}><FieldLabel help="Registra decisiones de validación, seguimiento o restricciones. No se publica." htmlFor="alert-notes">Notas internas</FieldLabel><textarea id="alert-notes" maxLength={5000} rows={3} {...register("notes")}/></div></div></section>
    <section className={styles.section}><h2>Evidencia y audiencias</h2><p>La API sólo permite enviar a revisión cuando toda la evidencia está validada o activa.</p><div className={styles.grid}><Checks disabled={mode==="edit"&&!auth.hasPermission("alerts:link-evidence")} label="Señales validadas" name="signalIds" options={options.signals} register={register}/><Checks disabled={mode==="edit"&&!auth.hasPermission("alerts:link-evidence")} label="Tendencias validadas o activas" name="trendIds" options={options.trends} register={register}/><Checks disabled={mode==="edit"&&!auth.hasPermission("alerts:link-evidence")} label="Audiencias" name="audienceCodes" options={options.audiences} register={register}/></div></section>
    <AssessmentField kind="alert" value={watched.assessment??null} error={errors.assessment?.message} onChange={value=>{form.setValue("assessment",value as AlertAssessment,{shouldDirty:true});form.clearErrors("assessment");}} /><section className={styles.section} aria-labelledby="alert-readiness"><h2 id="alert-readiness">Preparación para revisión</h2><ul>{readiness.map((item)=><li key={item.label}>{item.ready?"✓":"○"} {item.label}</li>)}</ul></section>
    <div className={styles.actions}><Link to={alert?`/admin/alertas/${alert.id}`:"/admin/alertas"}>Cancelar</Link><Button disabled={mutation.isPending} type="submit" variant="primary">{mutation.isPending?"Guardando…":mode==="create"?"Crear alerta":"Guardar cambios"}</Button></div></form>;
}

export function AlertFormPage({mode}:{mode:"create"|"edit"}){const auth=useAuth();const navigate=useNavigate();const raw=useParams().id;const id=raw&&/^\d+$/.test(raw)?Number(raw):null;const optionQuery=useQuery({queryKey:["alert-form-options"],queryFn:({signal})=>getAlertFormOptions(auth.token!,signal)});const detail=useQuery({queryKey:["admin-entity","alerts",id],queryFn:({signal})=>getAdminEntity("alerts",id!,auth.token!,signal),enabled:mode==="edit"&&Boolean(id)});const alert=detail.data?.data as Alert|undefined;const owner=alert?.creator?.id===auth.user?.id;const editable=alert?.status.code==="NEW"&&(owner||auth.hasPermission("alerts:validate"));if(mode==="edit"&&!id)return <PageFeedback title="Alerta no disponible" message="El identificador no es válido."/>;if(optionQuery.isPending||(mode==="edit"&&detail.isPending))return <PageFeedback title="Preparando formulario" message="Consultando catálogos, evidencia, audiencias y versión actual."/>;if(optionQuery.isError||(mode==="edit"&&detail.isError))return <PageFeedback title="Formulario no disponible" message="No fue posible consultar los datos necesarios."/>;if(mode==="edit"&&(!alert||!editable))return <PageFeedback title="Edición no permitida" message="Sólo el creador o un validador pueden editar alertas nuevas." actionLabel="Volver" onAction={()=>navigate("/admin/alertas")}/>;const base=optionQuery.data!;const options=alert?{...base,signals:mergeCurrent(base.signals,alert.signals),trends:mergeCurrent(base.trends,alert.trends)}:base;return <section className={styles.page}><header className={styles.header}><div><h1>{mode==="create"?"Nueva alerta":`Editar ${alert!.businessCode}`}</h1><p>Define la respuesta, evidencia y públicos objetivo antes de revisión.</p></div>{alert&&<div className={styles.ips}><span>Evidencia</span><strong>{alert.metrics.signalCount+alert.metrics.trendCount} relaciones</strong></div>}</header><AlertForm alert={alert} initial={alert?valuesFrom(alert):EMPTY} key={alert?.updatedAt??"new"} mode={mode} options={options}/></section>}
export const CreateAlertFormPage=()=> <AlertFormPage mode="create"/>;
export const EditAlertFormPage=()=> <AlertFormPage mode="edit"/>;
