const fs=require("node:fs/promises");const path=require("node:path");const crypto=require("node:crypto");
const repository=require("../repositories/media.repository");const {ValidationError,NotFoundError,ConcurrentModificationError}=require("../errors/apiError");const {parsePagination,buildPagination}=require("../utils/pagination");
const EXTENSIONS=new Map([["image/avif","avif"],["image/gif","gif"],["image/jpeg","jpg"],["image/png","png"],["image/webp","webp"],["application/pdf","pdf"],["text/plain","txt"],["text/csv","csv"],["application/vnd.openxmlformats-officedocument.wordprocessingml.document","docx"],["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","xlsx"]]);
const clean=(value,max,nullable=true)=>{const text=String(value??"").trim();if(!text)return nullable?null:"";if(text.length>max)throw new ValidationError("Los metadatos del medio no son válidos.");return text};
const bool=(value,defaultValue=false)=>value===undefined?defaultValue:value===true||value==="true"?true:value===false||value==="false"?false:(()=>{throw new ValidationError("La visibilidad del medio no es válida.")})();
function parseId(value){const id=Number(value);if(!Number.isSafeInteger(id)||id<1)throw new ValidationError("El identificador del medio no es válido.");return id}
class AdminMediaService{
 async list(query={}){const unexpected=Object.keys(query).filter((key)=>!["page","pageSize","search","kind","public"].includes(key));if(unexpected.length)throw new ValidationError("Los filtros de medios no son válidos.");const pagination=parsePagination(query);const search=query.search===undefined?null:clean(query.search,200);if(search&&search.length<2)throw new ValidationError("La búsqueda debe contener al menos dos caracteres.");const kind=query.kind===undefined?null:String(query.kind);if(kind&&!['image','file'].includes(kind))throw new ValidationError("El tipo de medio no es válido.");const isPublic=query.public===undefined?null:bool(query.public);const result=await repository.findAll({search,kind,isPublic},pagination);return {items:result.rows.map((row)=>this.map(row)),pagination:buildPagination(pagination.page,pagination.pageSize,result.totalItems)};}
 async get(rawId){const row=await repository.findById(parseId(rawId));if(!row)throw new NotFoundError("El medio no existe.");return this.map(row);}
 async create(file,body,user){if(!file)throw new ValidationError("Selecciona un archivo.",[{field:"file",message:"El archivo es obligatorio."}]);const extension=EXTENSIONS.get(file.mimetype);if(!extension)throw new ValidationError("El tipo de archivo no está permitido.");const filename=`${crypto.randomUUID()}.${extension}`;const root=path.resolve(process.env.MEDIA_ROOT||path.join(process.cwd(),"storage","media"));await fs.mkdir(root,{recursive:true});const temporary=path.join(root,`${filename}.upload`);const target=path.join(root,filename);await fs.writeFile(temporary,file.buffer,{flag:"wx"});try{await fs.rename(temporary,target);const id=await repository.create({filename,originalFilename:path.basename(file.originalname).slice(0,255),mimeType:file.mimetype,extension,storagePath:filename,sizeBytes:file.size,checksum:crypto.createHash("sha256").update(file.buffer).digest("hex"),userId:user.id,isPublic:bool(body.isPublic,false),title:clean(body.title,250),altText:clean(body.altText,500),description:clean(body.description,5000)});return this.get(id)}catch(error){await fs.rm(temporary,{force:true}).catch(()=>{});await fs.rm(target,{force:true}).catch(()=>{});throw error}}
 async update(rawId,input){const id=parseId(rawId);const current=await this.get(id);const keys=Object.keys(input);if(!keys.length||keys.some((key)=>!["title","altText","description","isPublic","updatedAt"].includes(key))||!input.updatedAt)throw new ValidationError("Los metadatos del medio no son válidos.");const data={title:Object.hasOwn(input,"title")?clean(input.title,250):current.title,altText:Object.hasOwn(input,"altText")?clean(input.altText,500):current.altText,description:Object.hasOwn(input,"description")?clean(input.description,5000):current.description,isPublic:Object.hasOwn(input,"isPublic")?bool(input.isPublic):current.isPublic,updatedAt:String(input.updatedAt)};if(await repository.update(id,data)!==1)throw new ConcurrentModificationError();return this.get(id)}
 map(row){return{id:Number(row.id_media),kind:String(row.mime_type??"").startsWith("image/")?"image":"file",title:row.title,altText:row.alt_text,description:row.description,filename:row.filename,originalFilename:row.original_filename,mimeType:row.mime_type,sizeBytes:row.size_bytes===null?null:Number(row.size_bytes),checksum:row.checksum,isPublic:row.is_public,uploader:row.uploaded_by===null?null:{id:Number(row.uploaded_by),name:row.uploader},url:String(row.mime_type??"").startsWith("image/")&&row.is_public?`/api/media/${row.id_media}`:null,downloadUrl:row.is_public?`/api/media/${row.id_media}/download`:null,createdAt:row.created_at,updatedAt:row.updated_at}}
}
module.exports=new AdminMediaService();
