import type { BlockDescriptor,ContentVersion } from "./editorial.types";

export interface BuilderBlock { key:string;type:BlockDescriptor["code"];schemaVersion:number;data:Record<string,unknown>;settings:Record<string,unknown>;isVisible:boolean;cssClass:string|null }
export interface BuilderSection { key:string;typeCode:string;title:string;isCollapsible:boolean;isVisible:boolean;settings:Record<string,unknown>;blocks:BuilderBlock[] }
export interface BuilderRelations {categoryIds:number[];signalIds:number[];trendIds:number[];alertIds:number[]}
export interface CompositionState {sections:BuilderSection[];relations:BuilderRelations}
let sequence=0;const key=(prefix:string)=>`${prefix}-${Date.now()}-${sequence++}`;
export const emptyRelations=():BuilderRelations=>({categoryIds:[],signalIds:[],trendIds:[],alertIds:[]});
export function fromVersion(version:ContentVersion):CompositionState{return {sections:version.sections.map((section)=>({key:key("section"),typeCode:section.type?.code??"custom",title:section.title??"",isCollapsible:section.isCollapsible,isVisible:section.isVisible,settings:section.settings,blocks:section.blocks.map((block)=>({key:key("block"),type:block.type.code,schemaVersion:block.schemaVersion,data:block.data,settings:block.settings,isVisible:block.isVisible,cssClass:block.cssClass??null}))})),relations:{categoryIds:version.relations.categories.flatMap((v)=>typeof v.id==="number"?[v.id]:[]),signalIds:version.relations.signals.map((v)=>v.id),trendIds:version.relations.trends.map((v)=>v.id),alertIds:version.relations.alerts.map((v)=>v.id)}}}
export function newSection(typeCode="custom"):BuilderSection{return {key:key("section"),typeCode,title:"",isCollapsible:false,isVisible:true,settings:{},blocks:[]}}
export function defaultData(type:string):Record<string,unknown>{if(type==="heading")return{text:"Nuevo encabezado",level:2};if(type==="paragraph")return{text:"Escribe el contenido.",format:"plain"};if(type==="quote")return{text:"Nueva cita",attribution:null,source:null};if(type==="list")return{style:"unordered",items:["Primer elemento"]};if(type==="callout")return{tone:"info",title:null,text:"Información destacada"};if(type==="divider")return{};if(type==="image")return{mediaId:1,alt:"Descripción de la imagen",caption:null,linkUrl:null};if(type==="file")return{mediaId:1,label:"Archivo",description:null};if(type==="table")return{caption:null,columns:[{key:"value",label:"Valor",type:"text"}],rows:[{value:"Dato"}]};if(type==="chart")return{chartType:"bar",title:null,labels:["Categoría"],series:[{name:"Serie",values:[1]}]};if(["signal","trend","alert"].includes(type))return{entityId:1,variant:"card",fields:{}};return{}}
export function newBlock(type:string,schemaVersion=1):BuilderBlock{return {key:key("block"),type:type as BlockDescriptor["code"],schemaVersion,data:defaultData(type),settings:{},isVisible:true,cssClass:null}}
export function move<T>(items:T[],index:number,direction:-1|1){const target=index+direction;if(target<0||target>=items.length)return items;const next=[...items];[next[index],next[target]]=[next[target],next[index]];return next}
export function toComposition(state:CompositionState,updatedAt:string){return {sections:state.sections.map((section)=>({typeCode:section.typeCode,title:section.title.trim()||null,isCollapsible:section.isCollapsible,isVisible:section.isVisible,settings:section.settings,blocks:section.blocks.map((block)=>({type:block.type,schemaVersion:block.schemaVersion,data:block.data,settings:block.settings,isVisible:block.isVisible,cssClass:block.cssClass}))})),relations:state.relations,updatedAt}}
export const signature=(state:CompositionState)=>JSON.stringify(state);
