import { useState } from "react";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { Link,useParams } from "react-router-dom";
import { isApiError } from "@/api";
import { PageFeedback } from "@/components/feedback/PageFeedback";
import { useAuth } from "@/features/auth/AuthContext";
import { EditorialSection } from "@/features/content/EditorialSection";
import type { PublicSection } from "@/features/content/types";
import { TransitionPanel } from "../TransitionPanel";
import type { TransitionOption } from "../types";
import { contentTransitionOptions } from "./editorial-transitions";
import { publicationReadiness,versionComparison } from "./editorial-readiness";
import { getContentPreview,getContentVersion,getInternalContent,listEditorialBlockTypes,transitionContent } from "./editorial.service";
import styles from "./EditorialAdmin.module.css";

export function ContentPreviewPage(){
  const auth=useAuth();const qc=useQueryClient();const raw=useParams().id;const id=raw&&/^\d+$/.test(raw)?Number(raw):null;const [transitionError,setTransitionError]=useState<string|null>(null);const [resetKey,setResetKey]=useState(0);
  const detail=useQuery({queryKey:["internal-content",id],queryFn:({signal})=>getInternalContent(id!,auth.token!,signal),enabled:Boolean(id)});
  const preview=useQuery({queryKey:["content-preview",id],queryFn:({signal})=>getContentPreview(id!,auth.token!,signal),enabled:Boolean(id)});
  const descriptors=useQuery({queryKey:["editorial-block-types"],queryFn:({signal})=>listEditorialBlockTypes(auth.token!,signal),enabled:Boolean(id)});
  const publishedId=detail.data?.data.publishedVersionId??null;
  const published=useQuery({queryKey:["content-version",id,publishedId],queryFn:({signal})=>getContentVersion(id!,publishedId!,auth.token!,signal),enabled:Boolean(id&&publishedId)});
  const state=useMutation({mutationFn:({option,notes}:{option:TransitionOption;notes:string|null})=>transitionContent(id!,option.code,notes,auth.token!),onSuccess:async()=>{setTransitionError(null);setResetKey((v)=>v+1);await Promise.all([qc.invalidateQueries({queryKey:["internal-content",id]}),qc.invalidateQueries({queryKey:["content-preview",id]}),qc.invalidateQueries({queryKey:["content-history",id]}),qc.invalidateQueries({queryKey:["content-versions",id]}),qc.invalidateQueries({queryKey:["internal-content-list"]})])},onError:(error)=>setTransitionError(isApiError(error)?error.message:"No fue posible cambiar el estado.")});
  if(!id)return <PageFeedback title="Vista previa no disponible" message="El identificador no es válido."/>;
  if(detail.isPending||preview.isPending||descriptors.isPending)return <PageFeedback title="Preparando revisión" message="Resolviendo la versión como se mostraría públicamente."/>;
  if(detail.isError||preview.isError||descriptors.isError||!detail.data.data.currentVersion)return <PageFeedback title="Vista previa no disponible" message="No fue posible preparar la revisión editorial." actionLabel="Reintentar" onAction={()=>void Promise.all([detail.refetch(),preview.refetch(),descriptors.refetch()])}/>;
  const content=detail.data.data;const version=content.currentVersion!;const result=preview.data.data;const sections=result.version.sections.filter((section)=>section.isVisible).map((section)=>({...section,blocks:section.blocks.filter((block)=>block.isVisible)})) as unknown as PublicSection[];const checks=publicationReadiness(content,version,descriptors.data.data);const blocked=checks.some((check)=>check.blocking&&!check.passed);const options=contentTransitionOptions(content.status.code).filter((option)=>auth.hasPermission(option.permission)&&!(blocked&&["SUBMIT_FOR_REVIEW","PUBLISH"].includes(option.code)));const comparison=versionComparison(version,published.data?.data??null);
  return <section className={styles.reviewPage}><header className={styles.header}><div><Link to={`/admin/contenido/${id}`}>← Volver al contenido</Link><h1>Revisión editorial</h1><p>Versión {version.number} · {content.status.name}</p></div>{content.status.code==="DRAFT"&&auth.hasPermission("content:update")&&<Link to={`/admin/contenido/${id}/composicion`}>Editar composición</Link>}</header><div className={styles.reviewLayout}><article className={styles.preview}><div className={styles.previewBanner}>Vista previa interna · resolución con las mismas reglas del portal público</div><header className={styles.previewHeader}><span>{result.type.name}</span><h1>{result.version.title}</h1>{result.version.summary&&<p>{result.version.summary}</p>}</header>{sections.length?<div>{sections.map((section)=><EditorialSection key={section.id} section={section}/>)}</div>:<div className={styles.empty}><h2>Versión sin composición publicable</h2><p>Revisa los bloques y sus referencias antes de continuar.</p></div>}</article><aside className={styles.reviewSidebar}><section className={styles.card}><h2>Preparación</h2><ul className={styles.checks}>{checks.map((check)=><li data-passed={check.passed} key={check.code}><span aria-hidden="true">{check.passed?"✓":"!"}</span><div>{check.label}{!check.blocking&&!check.passed&&<small>Recomendado</small>}</div></li>)}</ul>{blocked&&<p className={styles.error}>Corrige los requisitos bloqueantes antes de enviar o publicar.</p>}</section><section className={styles.card}><h2>Comparación de versiones</h2>{comparison.published?<><p>Versión de trabajo frente a la versión pública vigente.</p><dl className={styles.comparison}><div><dt>Secciones visibles</dt><dd>{comparison.current.sections} / {comparison.published.sections}</dd></div><div><dt>Bloques visibles</dt><dd>{comparison.current.blocks} / {comparison.published.blocks}</dd></div><div><dt>Referencias</dt><dd>{comparison.current.relations} / {comparison.published.relations}</dd></div><div><dt>Metadatos</dt><dd>{comparison.titleChanged||comparison.summaryChanged?"Con cambios":"Sin cambios"}</dd></div></dl></>:<p>Este contenido todavía no tiene una versión publicada.</p>}{published.isError&&<p className={styles.error}>No fue posible cargar la versión publicada para comparar.</p>}</section><section className={styles.card}><h2>Acciones editoriales</h2><TransitionPanel busy={state.isPending} error={transitionError} key={resetKey} onConfirm={(option,notes)=>state.mutate({option,notes})} options={options}/></section></aside></div></section>;
}
