import {useRef,useState} from 'react';
import {evaluateTrend,type TrendAssessment,type TrendEvidence} from './trend-assessment';
import styles from './AssessmentField.module.css';
export function TrendAssessmentField({value,signals,onChange,error}:{value:TrendAssessment|null;signals:TrendEvidence[];onChange:(v:TrendAssessment)=>void;error?:string}){
 const dialog=useRef<HTMLDialogElement>(null),button=useRef<HTMLButtonElement>(null);
 const [nature,setNature]=useState<TrendAssessment['nature']|''>('');
 const result=nature?evaluateTrend({version:'2026-07-21',nature},signals):null;
 const saved=value?evaluateTrend(value,signals):null;
 const close=()=>{dialog.current?.close();button.current?.focus();};
 return <section className={styles.container}><div className={styles.overview}><div><h2>Valoración de la tendencia</h2><p>{saved?`${saved.direction} · ${saved.maturity}`:'Evalúa la naturaleza del cambio y revisa la evidencia.'}</p></div><button ref={button} type="button" onClick={()=>{setNature(value?.nature??'');dialog.current?.showModal();}}>{value?'Revisar valoración':'Capturar valoración'}</button></div>{error&&<p role="alert">{error}</p>}
 <dialog ref={dialog} className={styles.dialog} aria-labelledby="trend-assessment-title" onCancel={close} onClose={()=>button.current?.focus()}><header className={styles.header}><h2 id="trend-assessment-title">Valoración de la tendencia</h2><button type="button" onClick={close}>Cerrar</button></header><div className={styles.body}><div className={styles.criterion}><label htmlFor="trend-nature"><strong>Naturaleza del cambio</strong><span>Incremental: evolución de una tecnología, proceso, producto o categoría existente. Radical: al menos una señal incorpora un elemento no registrado previamente dentro del FCV.</span></label><select id="trend-nature" value={nature} onChange={e=>setNature(e.target.value as TrendAssessment['nature'])}><option value="">Sin responder</option><option value="INCREMENTAL">Incremental</option><option value="RADICAL">Radical</option></select></div><p>La dirección compara las señales capturadas en las dos últimas ventanas consecutivas de 30 días. Un flujo igual o mayor se considera positivo.</p>{result&&<><h3>Dirección: {result.direction}</h3><p>Periodo actual: {result.current} señales · Periodo anterior: {result.previous} señales.</p><h3>Madurez: {result.maturity}</h3><p>{result.count} señales · {result.months} meses entre la primera y la última publicación · {result.sources} fuentes distintas.</p></>}<table><caption>Se deben cumplir los tres umbrales simultáneamente</caption><thead><tr><th>Nivel</th><th>Señales</th><th>Antigüedad</th><th>Fuentes</th></tr></thead><tbody><tr><th>Emergente</th><td>3</td><td>6 meses</td><td>2</td></tr><tr><th>En consolidación</th><td>5</td><td>12 meses</td><td>3</td></tr><tr><th>Consolidada</th><td>8</td><td>24 meses</td><td>5</td></tr></tbody></table><p>El cálculo utiliza las señales validadas seleccionadas. Las fuentes distintas requieren revisión del analista para confirmar su independencia.</p></div><footer className={styles.footer}><span aria-live="polite">{result?`${result.direction} · ${result.maturity}`:'Selecciona la naturaleza del cambio.'}</span><div className={styles.actions}><button type="button" onClick={close}>Cancelar</button><button type="button" disabled={!nature} onClick={()=>{if(nature){onChange({version:'2026-07-21',nature});close();}}}>Aplicar valoración</button></div></footer></dialog></section>;
}
